DesignPatternsMVC/Models/ErrorViewModel.cs
namespace DesignPatternsMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesignPatternsMVC/Models/ViewModels/BeerViewModel.cs
namespace DesignPatternsMVC.Models.ViewModels
{
    public class BeerViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
    }
}

DesignPatternsMVC/Models/ViewModels/FormBeerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DesignPatternsMVC.Models.ViewModels
{
    public class FormBeerViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Estilo")]
        public string Style { get; set; }

        [Display(Name = "Marca")]
        public Guid? BrandId { get; set; }

        [Display(Name = "Otra marca")]
        public string OtherBrand { get; set; }
    }
}

DesignPatternsMVC/Controllers/BeerController.cs
using DesignPatternsMVC.Models.ViewModels;
using DesignPatternsMVC.Strategies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RepositoryApp;
using RepositoryApp.Models;

namespace DesignPatternsMVC.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BeerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<BeerViewModel> beers = from d in _unitOfWork.Beers.Get()
                                               select new BeerViewModel
                                               {
                                                   Id = d.BeerId,
                                                   Name = d.Name,
                                                   Style = d.Style
                                               };

            return View("Index", beers);
        }

        public IActionResult Add()
        {
            GetBrandsData();
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormBeerViewModel beerVM)
        {
            if (!ModelState.IsValid)
            {
                GetBrandsData();
                return View("Add", beerVM);
            }

            var beerContext = beerVM.BrandId == null ?
                                new BeerContext(new BeerWithNewBrandStrategy()) :
                                new BeerContext(new BeerStrategy());

            beerContext.Add(beerVM, _unitOfWork);

            return RedirectToAction("Index");
        }

        #region Helpers
        private void GetBrandsData()
        {
            IEnumerable<Brand> brands = _unitOfWork.Brands.Get();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
        }
        #endregion
    }
}

DesignPatternsMVC/Controllers/GeneratorFileController.cs
using Microsoft.AspNetCore.Mvc;
using RepositoryApp;
using Tools.Generator;

namespace DesignPatternsMVC.Controllers
{
    public class GeneratorFileController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly GeneratorConcreteBuilder _generatorConcreteBuilder;

        public IActionResult Index()
        {
            return View();
        }

        public GeneratorFileController(IUnitOfWork unitOfWork, GeneratorConcreteBuilder generatorConcreteBuilder)
        {
            _unitOfWork = unitOfWork;
            _generatorConcreteBuilder = generatorConcreteBuilder;
        }

        public IActionResult CreateFile(int optionFile)
        {
            try
            {
                var beers = _unitOfWork.Beers.Get();
                List<string> content = beers.Select(b => b.Name).ToList();
                string path = "file" + DateTime.Now.Ticks + new Random().Next(1000) + ".txt";
                var generatorDirector = new GeneratorDirector(_generatorConcreteBuilder);

                if (optionFile == 1)
                    generatorDirector.CreateSimpleJsonGenerator(content, path);
                else
                    generatorDirector.CreateSimplePipeGenerator(content, path);

                //Se obtiene el objeto final después de haber seteadp las variables y ejecutado ciertos métodos
                Generator generator = _generatorConcreteBuilder.GetGenerator();
                generator.Save();

                return Json("Archivo generado.");
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

DesignPatternsMVC/Controllers/HomeController.cs
using DesignPatternsMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DesignPatternsMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesignPatternsMVC/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Xml.Schema;
using Tools.Earn;

namespace DesignPatternsMVC.Controllers
{
    public class ProductDetailController : Controller
    {
        private EarnFactory _localEarnFactory;
        private EarnFactory _foreignFactory;

        //Aquí la dependency injection ya crea el objeto cuando se realiza una solicitud 
        public ProductDetailController(LocalEarnFactory localEarnFactory, ForeignEarnFactory foreignFactory)
        {
            _localEarnFactory = localEarnFactory;
            _foreignFactory = foreignFactory;
        }

        //la variable decimal total es el precio del producto.
        public IActionResult Index(decimal total)
        {
            // Factories

            // Esta declaración no es necesaria dentro de la clase ProductDetailController por que ahora se crea desde antes y ProductDetailController la recibe.
            //LocalEarnFactory localEarnFactory = new(0.20m);
            //ForeignEarnFactory frEarnFactoy = new(0.20m, 1.25m);

            // Products (objeto(s) que crea la fábrica)
            var localEarn = _localEarnFactory.GetEarn();
            var frEarn = _foreignFactory.GetEarn();

            //total
            ViewBag.totalLocal = total + localEarn.Earn(total);
            ViewBag.totalForeign = total + frEarn.Earn(total);

            return View();
        }
    }
}

DesignPatternsMVC/Views/Beer/Add.cshtml
@model DesignPatternsMVC.Models.ViewModels.FormBeerViewModel

<form asp-controller="Beer" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId" asp-items="@ViewBag.Brands">
            <option value="">--- Selecciona Marca ---</option>
        </select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>

    <br />

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
</form>

DesignPatternsMVC/Views/Beer/Index.cshtml
@using DesignPatternsMVC.Models.ViewModels
@model IEnumerable<BeerViewModel>

	<div class="row">
		<div class="col-12">
			<a class="btn btn-primary" href="~/Beer/Add">Nueva Cerveza</a>
		</div>
	</div>

	<div class="row">
		<div class="col-12">
			<table class="table">
				<tr>
					<th>Nombre</th>
				</tr>
			@foreach(var beer in Model)
			{
				<tr>
					<td>@beer.Name</td>
				</tr>
			}
			</table>
		</div>
	</div>

DesignPatternsMVC/Views/GeneratorFile/Index.cshtml
<div class="row">
    <div class="col-8 offset-2">
        <div class="form-groupd">  
            <select id="optionFile" class="form-control">
                <option value="1">Json</option>
                <option value="2">Pipe</option>
            </select>
        </div>
        <div class="">
            <button class="btn btn-success" onclick="generate()">Generar</button>
        </div>
    </div>
</div>

<script>
    function generate(){
        let optionFile = document.getElementById("optionFile").value;
        fetch("@Url.Content("~/GeneratorFile/CreateFile")" + "?optionFile=" + optionFile)
            .then(res => res.json())
            .then(json => alert(json));
    }
</script>

DesignPatternsMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DesignPatternsMVC/Views/ProductDetail/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    decimal totalLocal = (decimal)ViewBag.totalLocal;
    decimal totalForeign = (decimal)ViewBag.totalForeign;
}

<div class="row">
    <div class="col-12">
        <label>Total Local:</label>
        <b>@totalLocal</b>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <label>Total Extranjero:</label>
        <b>@totalForeign</b>
    </div>
</div>

DesignPatternsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignPatternsMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesignPatternsMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignPatternsMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DesignPatternsMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>